name: sba-client-dev

services:
  # Ang Gateway
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client

  # Ang Vite Dev Server
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Ito ang Volume: Sync ang local files sa container
      - /app/node_modules # Huwag i-sync ang node_modules (para mabilis)
    environment:
      - VITE_PORT=5173
